In [75]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import geopandas as gpd
import seaborn as sns

from datetime import datetime, timedelta

plt.style.use('ggplot')

In [76]:
# Путь до папки с данными
path_to_data = 'datasets/'

In [77]:
data = pd.read_csv(path_to_data + 'meteo/4403131.csv', ';', index_col = 'time')
data.columns

Index(['station_name', 'station_id', 'visibility_distance',
       'visibility_distance_quality', 'wind_direction',
       'wind_direction_quality', 'wind_speed_avg', 'wind_speed_avg_quality',
       'wind_speed_sign', 'wind_speed_max', 'wind_speed_max_quality',
       'wind_speed_max_sign', 'precipitation_amount',
       'precipitation_amount_quality', 'temperature_ground',
       'temperature_ground_quality', 'temperature_air',
       'temperature_air_quality', 'humidity', 'humidity_quality'],
      dtype='object')

In [78]:
data = data.sort_values(by=['station_id','time'])
data

,station_name,station_id,visibility_distance,visibility_distance_quality,wind_direction,wind_direction_quality,wind_speed_avg,wind_speed_avg_quality,wind_speed_sign,wind_speed_max,wind_speed_max_quality,wind_speed_max_sign,precipitation_amount,precipitation_amount_quality,temperature_ground,temperature_ground_quality,temperature_air,temperature_air_quality,humidity,humidity_quality
time,,,,,,,,,,,,,,,,,,,,
1987-02-01 00:00:00,POLTA26,4403131,83.0,0,230.0,0,4.0,0,NaN,8.0,0,NaN,NaN,5,-24.5,0,-18.1,0,46.0,0
1987-02-01 03:00:00,POLTA26,4403131,99.0,0,230.0,0,1.0,0,NaN,3.0,0,NaN,NaN,5,-24.0,0,-20.3,0,52.0,0
1987-02-01 06:00:00,POLTA26,4403131,99.0,0,280.0,0,2.0,0,NaN,5.0,0,NaN,NaN,5,-6.0,0,-10.7,0,42.0,0
1987-02-01 09:00:00,POLTA26,4403131,99.0,0,20.0,0,1.0,0,NaN,3.0,0,NaN,NaN,5,-6.0,0,-6.9,0,32.0,0
1987-02-01 12:00:00,POLTA26,4403131,99.0,0,110.0,0,3.0,0,NaN,8.0,0,NaN,NaN,5,-13.5,0,-9.7,0,44.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018-12-31 09:00:00,POLTA26,4403131,NaN,5,280.0,0,2.0,0,NaN,7.0,0,NaN,NaN,5,-13.7,0,-10.5,0,31.0,0
2018-12-31 12:00:00,POLTA26,4403131,NaN,7,NaN,7,NaN,7,NaN,NaN,7,NaN,NaN,7,NaN,7,NaN,7,NaN,7
2018-12-31 15:00:00,POLTA26,4403131,NaN,5,0.0,0,0.0,0,NaN,3.0,0,NaN,NaN,5,-20.1,0,-17.1,0,60.0,0
2018-12-31 18:00:00,POLTA26,4403131,NaN,7,NaN,7,NaN,7,NaN,NaN,7,NaN,NaN,7,NaN,7,NaN,7,NaN,7
2018-12-31 21:00:00,POLTA26,4403131,NaN,5,0.0,0,0.0,0,NaN,3.0,0,NaN,NaN,5,-20.0,0,-18.9,0,57.0,0

Helpers

In [79]:
df = data.copy()

In [2]:
def nse(simulations, evaluation):
    nse = 1 - (
            np.sum((evaluation - simulations) ** 2, axis=0, dtype=np.float64)
            / np.sum((evaluation - np.mean(evaluation)) ** 2, dtype=np.float64)
    )
    return nse

In [1]:
def na_heat_map(df, figsize=(20,12), cmap='viridis'):
    fig, ax = plt.subplots(figsize=figsize)
    sns_heatmap = sns.heatmap(df, yticklabels = False, cbar = False, cmap = cmap)

In [81]:
class TimeSeriesExtracter():
    def __init__(self, id_col, x_cols, deltas, lags):
        self.id_col = id_col
        self.x_cols = x_cols
        self.deltas = deltas
        self.lags = lags
        pass
    
    def fit(self, df, **fit_params):
        self.df = df.copy()
        return self
    
    def transform(self, **transform_params):
        for x, d, lag, in zip(self.x_cols, self.deltas, self.lags):
            for i in range(d, d + lag):
                self.df[x + "_t_" + str(i)] = self.df.groupby(self.id_col)[x].shift(i)
                
        return self.df
    
    def fit_transform(self, df):
        return self.fit(df).transform()

In [87]:
d = pd.read_csv(path_to_data + 'hydro/05311_disch_d.csv', ';', index_col = 'time')
d

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 0: invalid continuation byte

In [82]:
TimeSeriesExtracter('station_id', ['temperature_ground'], [1], [3]).fit_transform(df)

,station_name,station_id,visibility_distance,visibility_distance_quality,wind_direction,wind_direction_quality,wind_speed_avg,wind_speed_avg_quality,wind_speed_sign,wind_speed_max,...,precipitation_amount_quality,temperature_ground,temperature_ground_quality,temperature_air,temperature_air_quality,humidity,humidity_quality,temperature_ground_t_1,temperature_ground_t_2,temperature_ground_t_3
time,,,,,,,,,,,,,,,,,,,,,
1987-02-01 00:00:00,POLTA26,4403131,83.0,0,230.0,0,4.0,0,NaN,8.0,...,5,-24.5,0,-18.1,0,46.0,0,NaN,NaN,NaN
1987-02-01 03:00:00,POLTA26,4403131,99.0,0,230.0,0,1.0,0,NaN,3.0,...,5,-24.0,0,-20.3,0,52.0,0,-24.5,NaN,NaN
1987-02-01 06:00:00,POLTA26,4403131,99.0,0,280.0,0,2.0,0,NaN,5.0,...,5,-6.0,0,-10.7,0,42.0,0,-24.0,-24.5,NaN
1987-02-01 09:00:00,POLTA26,4403131,99.0,0,20.0,0,1.0,0,NaN,3.0,...,5,-6.0,0,-6.9,0,32.0,0,-6.0,-24.0,-24.5
1987-02-01 12:00:00,POLTA26,4403131,99.0,0,110.0,0,3.0,0,NaN,8.0,...,5,-13.5,0,-9.7,0,44.0,0,-6.0,-6.0,-24.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018-12-31 09:00:00,POLTA26,4403131,NaN,5,280.0,0,2.0,0,NaN,7.0,...,5,-13.7,0,-10.5,0,31.0,0,NaN,-1.4,NaN
2018-12-31 12:00:00,POLTA26,4403131,NaN,7,NaN,7,NaN,7,NaN,NaN,...,7,NaN,7,NaN,7,NaN,7,-13.7,NaN,-1.4
2018-12-31 15:00:00,POLTA26,4403131,NaN,5,0.0,0,0.0,0,NaN,3.0,...,5,-20.1,0,-17.1,0,60.0,0,NaN,-13.7,NaN
2018-12-31 18:00:00,POLTA26,4403131,NaN,7,NaN,7,NaN,7,NaN,NaN,...,7,NaN,7,NaN,7,NaN,7,-20.1,NaN,-13.7
2018-12-31 21:00:00,POLTA26,4403131,NaN,5,0.0,0,0.0,0,NaN,3.0,...,5,-20.0,0,-18.9,0,57.0,0,NaN,-20.1,NaN

In [83]:
# def extract_timeseries_feautres(df, id_col, x_cols, deltas, lags):
#     df_ = df.copy()
#     for x, d, lag, in zip(x_cols, deltas, lags):
#         for i in range(d, d + lag):
#             df_[x + "_t_" + str(i)] = data.groupby(id_col)[x].shift(i)
#     return df_
# TimeSeriesExtracter('station_id', ['temperature_ground'], [1], [3]).fit_transform(df)
#extract_timeseries_feautres(df, 'station_id', ['temperature_ground'], [1], [3])

In [84]:
df

,station_name,station_id,visibility_distance,visibility_distance_quality,wind_direction,wind_direction_quality,wind_speed_avg,wind_speed_avg_quality,wind_speed_sign,wind_speed_max,wind_speed_max_quality,wind_speed_max_sign,precipitation_amount,precipitation_amount_quality,temperature_ground,temperature_ground_quality,temperature_air,temperature_air_quality,humidity,humidity_quality
time,,,,,,,,,,,,,,,,,,,,
1987-02-01 00:00:00,POLTA26,4403131,83.0,0,230.0,0,4.0,0,NaN,8.0,0,NaN,NaN,5,-24.5,0,-18.1,0,46.0,0
1987-02-01 03:00:00,POLTA26,4403131,99.0,0,230.0,0,1.0,0,NaN,3.0,0,NaN,NaN,5,-24.0,0,-20.3,0,52.0,0
1987-02-01 06:00:00,POLTA26,4403131,99.0,0,280.0,0,2.0,0,NaN,5.0,0,NaN,NaN,5,-6.0,0,-10.7,0,42.0,0
1987-02-01 09:00:00,POLTA26,4403131,99.0,0,20.0,0,1.0,0,NaN,3.0,0,NaN,NaN,5,-6.0,0,-6.9,0,32.0,0
1987-02-01 12:00:00,POLTA26,4403131,99.0,0,110.0,0,3.0,0,NaN,8.0,0,NaN,NaN,5,-13.5,0,-9.7,0,44.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018-12-31 09:00:00,POLTA26,4403131,NaN,5,280.0,0,2.0,0,NaN,7.0,0,NaN,NaN,5,-13.7,0,-10.5,0,31.0,0
2018-12-31 12:00:00,POLTA26,4403131,NaN,7,NaN,7,NaN,7,NaN,NaN,7,NaN,NaN,7,NaN,7,NaN,7,NaN,7
2018-12-31 15:00:00,POLTA26,4403131,NaN,5,0.0,0,0.0,0,NaN,3.0,0,NaN,NaN,5,-20.1,0,-17.1,0,60.0,0
2018-12-31 18:00:00,POLTA26,4403131,NaN,7,NaN,7,NaN,7,NaN,NaN,7,NaN,NaN,7,NaN,7,NaN,7,NaN,7
2018-12-31 21:00:00,POLTA26,4403131,NaN,5,0.0,0,0.0,0,NaN,3.0,0,NaN,NaN,5,-20.0,0,-18.9,0,57.0,0